name: BuildAndPublish
on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*
  pull_request: 
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Setup dotnet 3
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.x

      # - name: Setup dotnet 5
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 5.0.x

      - name: build and publish
        shell: powershell
        run: |
          dotnet tool restore
          ./build.ps1 -nugetPublish $false -nugetApiKey ${{ secrets.NUGET_API_KEY }}

      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./src/DotNetCoreConfigVault.Tests/TestResults/coverage.info 